project_id = "hluibrulhhondkyfbhbh"

[api]
enabled = true
port = 54321
schemas = ["public", "graphql_public"]
extra_search_path = ["public", "extensions"]
max_rows = 1000

[auth]
enabled = true
site_url = "http://localhost:3000"
additional_redirect_urls = ["https://localhost:3000"]
jwt_expiry = 3600
enable_refresh_token_rotation = true
refresh_token_reuse_interval = 10

[functions.mpesa-payment]
verify_jwt = false

[functions.mpesa-callback]
verify_jwt = false

[functions.send-order-approval-email]
verify_jwt = false